[project]
name = "gpx-vis"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "colormap>=1.3.0",
    "folium>=0.19.5",
    "gpxpy>=1.6.2",
    "matplotlib>=3.10.1",
    "numpy>=2.2.4",
]
